project:
  type: website
  execute-dir: project
  output-dir: _site
  preview:
    port: 8000
    host: 127.0.0.1
    browser: true
    watch-inputs: true
    navigate: true

website:
  # title: "Hamburg 💞 Rotterdam City Guide"
  description: "Hamburg 💞 Rotterdam City Guide"
  site-url: "https://lennartwittkuhn.com/uhh-eur-city-guide/"
  repo-url: "https://github.com/lnnrtwttkhn/uhh-eur-city-guide/"
  repo-branch: main
  issue-url: "https://github.com/lnnrtwttkhn/uhh-eur-city-guide/issues"
  repo-actions: [edit, source, issue]
  reader-mode: false
  navbar:
    background: light
    search: true
    left:
      - href: index.qmd
        text: "{{< fa tree-city >}} City Guide"
    right:
      - icon: envelope
        aria-label: Email
        href: "{{< var mailto >}}"
      - icon: github
        aria-label: GitHub
        href: "{{< var repo-url >}}"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    link-external-newwindow: true
    include-after-body: plausible.html
